spring.application.name=PROYECTOAPI

# 1. Configuración de la Fuente de Datos (H2 In-Memory temporal para pruebas libres)
spring.datasource.url=jdbc:h2:mem:ecommerce_db
spring.datasource.username=sa
spring.datasource.password=

# 2. Driver específico de H2
spring.datasource.driver-class-name=org.h2.Driver

# Consola H2 para poder ver la DB en el navegador si lo deseas:
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true