spring.application.name=PROYECTOAPI

# 1. Configuración de la Fuente de Datos
# Usamos el puerto 3306 como me confirmaste
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_api?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# 2. Driver específico
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true